# Generated by Django 5.2.4 on 2025-09-07 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_product_current_lowest_price_pricealert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_lowest_price',
        ),
        migrations.AlterUniqueTogether(
            name='pricealert',
            unique_together={('user', 'product')},
        ),
    ]
