# Generated by Django 5.2.4 on 2025-09-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_product_current_lowest_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
